credentials:
  usernames:
    almir:
      email: crazyself@gmail.com
      name: Almir Martins
      password: $2b$12$CbBhngLkOlW0EGUuCIDdNONUOyskrER6b0ql6314udQLDv893yGCa # To be replaced with hashed password
    leo:
      email: leonardoaai@yahoo.com
      name: Leonardo Cordeiro
      password: $2b$12$UHgcQK9SJx1.s/xj8kE33u/YOyzXmCDNb4MjAXuZnMsMAdUOc1WWC # To be replaced with hashed password
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - crazyself@gmail.com